### ISSUE TITLE
return error when the country not in the table

### ISSUE THREAD

**Issue by ggg5269** [fdfoneill/wasdeparser#1]
when the country is not in the WASDE report, like Pakistan was been removed since 2019/5/10, the program will give the error in  
`sheet.write(row,col,report['data'][region][i])`
in Sheetmaker.py

so I make some changes in this line to 

```
for region in self.crop_regions[crop]:
      region_i = None
      try:
	      region_i = report['data'][region][i]
      except:
	      pass
      sheet.write(row,col,region_i)
```
maybe you can put this into your code as well. : )
BTW, this package did help me a lot, tks ~

**Comment by fdfoneill** [comment]
Change implemented, thanks so much for your help!
